### PR TITLE
Feature/parse large files low memory

### PR DESCRIPTION
**Pull request by willgdjones**
This PR implements functionality to efficiently parse large VCF files without needing to decompress them. It also provides functionality to specify a set of rsids to extract from the file:
```
df = SNPs(bytes_data, rsids=["rs1", "rs2"]
```

This functionality only works when feeding in a `bytes_data` object, which needs to be a valid, gzip compressed byte-string.

I am able to extract rsids from an output of an imputation pipeline which is a VCF file ~450mb compressed in ~ 1 minute.

This should be merged after #32.

### CODE REVIEW

**Comment by willgdjones** [comment]
I think I need to match my `black` settings with yours. What editor settings do you use?

**Comment by apriha** [comment]
> I think I need to match my `black` settings with yours. What editor settings do you use?

Just the default settings, integrated with PyCharm as an external tool: https://github.com/psf/black#editor-integration . You can run `black --check --diff .` before a commit to see if it would reformat any files.

**Comment by willgdjones** [comment]
Ok! I've matched the settings now.

**Comment by willgdjones** [comment]
Those changes look good @apriha !

**Pull request merged**
