### PR TITLE
Feature/accept bytesdata

### PR DESCRIPTION
**Pull request by willgdjones**
This PR implements the feature to:
* Read input as a byte-string.
```
with open("tests/input/chromosomes.csv", 'r') as f:
    self.snps_buffer = SNPs(f.read().encode('utf-8'))
```
It will automatically detect whether or not the input is a byte-string and checks whether the received byte-string is valid zip or gzip, and handles it accordingly.
* Write output to a memory buffer.
```
out = io.StringIO()
snps.save_snps(out, buffer=True)
print(out.read())
# '# Generated by snps v0.1.1...'
```

The PR also implements a piece of functionality which I have found useful, which is to only detect the source of a provided file instead of additionally loading the SNPs into a pandas data frame. I found that this took sometimes ~1 minute to ingest AncestryDNA files, which all I wanted to do was to read the first few lines of the file to detect the source. An example way to use it is:

```
snps_only_detect_source = SNPs("tests/input/chromosomes.csv", only_detect_source=True)`
snps_only_detect_source.snps
# Empty DataFrame
# Columns: []
# Index: []
snps_only_detect_source.source
# 'generic'
```

### CODE REVIEW

**Comment by apriha** [comment]
@willgdjones , this PR looks really good, thanks! I made some updates - check them out and let me know what you think. Thanks again!

**Comment by apriha** [comment]
I wonder if it would be more succinct to detect the memory buffer with `save_snps`, vs. specifying as a parameter?

**Comment by apriha** [comment]
Also, if there are better names for functions now that the functionality has been expanded, we could rename those, perhaps with aliases of the current names for backwards compatibility.

**Comment by willgdjones** [comment]
Hi @apriha - apologies for not being able to take a look at the points that you raise! I think they make a lot of sense. Thanks for doing so.

**Comment by apriha** [comment]
Hey @willgdjones , no problems. Thanks again for the help and contributions!

**Pull request merged**
