### PR TITLE
Feature/sano updates

### PR DESCRIPTION
**Pull request by willgdjones**
Updates involving:
* Supporting TellmeGen data files
* Supporting older MyHeritage files
* Detecting build 37/38 VCF files
* VCF parsing fixes
* Add a CircleCi support

### CODE REVIEW

**Comment by willgdjones** [comment]
We'll do that!

**Comment by apriha** [comment]
Hi @willgdjones , could you check to make sure that the extra-quoted MyHeritage file looks correct? Also, feel free to update `CONTRIBUTORS.rst`.

This PR should then be ready to merge. Thanks again!

**Comment by willgdjones** [comment]
HI @apriha - thanks for pushing this through and sorry I was slow to find the right format of that MyHeritage file.

Those changes look good to me, including that example file. We'll update `CONTRIBUTORS.rst` on the next contribution because we've got some more coming!

**Comment by apriha** [comment]
No problems and that sounds great @willgdjones . Thanks!

**Pull request merged**
