### PR TITLE
Support for Codigo46 and LivingDNA files

### PR DESCRIPTION
**Pull request by willgdjones**
This PR adds support for Codigo46 and LivingDNA. Codigo46 is a Mexican DTC genomics provider that uses the Illumina GSA chip. LivingDNA is a UK based DTC provider with a focus on ancestry.

Codigo46 files are non-standard:

```
[Header]
GSGT Version	2.0.2
Processing Date	2018-09-18 19:14:56
Content		CODIGO46_2017_01_20011739X343381_B1.bpm
Num SNPs	642824
Total SNPs	642824
Num Samples	1
Total Samples	1
[Data]
SNP Name	Sample ID	Allele1 - Plus	Allele2 - Plus
1:100292476	102017000000550	A	A
1:101064936	102017000000550	A	A
1:103380393	102017000000550	G	G
...
GSA-rs41440050	102017000000550	T	T
GSA-rs4144116	102017000000550	A	G
GSA-rs4144213	102017000000550	T	T
...
rs4375601	102017000000550	C	C
rs4375615	102017000000550	G	G
rs4375628	102017000000550	T	T
rs4375811	102017000000550	A	A
```

The `SNP Name` column contains a mixture of keys with the format `chr:pos`, `GSA-rsXXX` and `rsXXX`. Fortunately, there exists a mapping on the [Illumina website](http://emea.support.illumina.com/array/array_kits/infinium-global-screening-array/downloads.html) between these keys and the conventional rsids along with a mapping for chr:pos. We (Sano Genetics) are happy to host these mappings publicly for users of this package to use, in case they disappear from the Illumina website. They are ~3mb compressed for the rsid map and 8mb compressed for the chr:pos map.

LivingDNA files are very similar to 23andMe files and are parsed in a similar manner.

```
# Living DNA customer genotype data download file version: 1.0.2
# File creation date: 9-3-2019
# Genotype chip: Sirius
# The content of this file is subject to updates and changes depending on the time of download.
# This genotype data should be treated as personal information.
# This genotype data is not suitable for clinical/medical research or diagnosis.
# The user assumes all responsibility for the security of this file.
# Please refer to the Living DNA Terms and Conditions on our website (www.livingdna.com) for more information.
# Human Genome Reference Build 37 (GRCh37.p13).
# Genotypes are presented on the forward strand.
#
# rsid	chromosome	position	genotype
rs3131972	1	752721	GG
rs114525117	1	759036	GG
rs115991721	1	767096	AA
rs114498757	1	776112	TT
rs141175086	1	780397	CC
rs114777415	1	785140	AA
rs116146680	1	794374	TT
rs79373928	1	801536	TT
rs7542092	1	829667	CC
rs116452738	1	834830	GG
rs72631887	1	835092	TT
rs4970383	1	838555	AA
rs4970382	1	840753	CC
```

I have also added the company that I am co-founder and CTO of, Sano Genetics, to the acknowledgements section!

### CODE REVIEW

**Comment by apriha** [comment]
@willgdjones , thanks for the PR - it looks good! Thanks also for hosting the Codigo46 resources; I moved the code to download and load those files to `Resources`.

Would you be able to update the Codigo46 test to read in a file that matches the `generic_snps` dataframe? Thanks again!

**Comment by willgdjones** [comment]
> Would you be able to update the Codigo46 test to read in a file that matches the generic_snps dataframe? Thanks again!

I can do that!

**Comment by willgdjones** [comment]
I have just taken another look, and I have realised that it is not trivial to set up the Codigo46 file to match the `generic_snps` dataframe. The `SNP Name` column gets converted into the rsid and chr:pos, via the mapping files. Therefore I would need to modify the map itself so that the `SNP Name` values of the existing Codigo46 file map to the expected values in  `generic_snps`. Modifying the mapping files is difficult, because they are downloaded. Let me know what you think works best!

**Comment by apriha** [comment]
No problems, I added some test resource files that will work with the `generic_snps` dataframe. Can you confirm that Codigo46 NaN values are `--` in each allele column? Thanks again!

**Comment by apriha** [comment]
Merging this PR. Thanks @willgdjones !

**Pull request merged**
