### PR TITLE
Investigate updating thresholds and methods for `determine_sex`; fixes #49

### LINKED ISSUE #49: Investigate updating thresholds and methods for `determine_sex`
The thresholds and methods for determining the sex of a genotype should be reinvestigated. See comments regarding misidentification of Female genotypes as Male at #48.

To fix this, I propose investigating the optimal thresholds for these parameters using data from [openSNP](https://opensnp.org) and updating `determine_sex` as necessary.

Moreover, the script documenting the analysis and its results should be added to the repo as an example.

### PR DESCRIPTION
**Pull request by apriha**
This PR investigates the thresholds used to determine if a genotype is Male or Female. An analysis of [openSNP](https://opensnp.org) data is included and the thresholds and methods for `determine_sex` are updated.

### CODE REVIEW

**Comment by apriha** [comment]
It seems that a threshold of `0.03` for `Heterozygous X SNPs / X SNPs` and `0.3` for `Y SNPs not null / Y SNPs` would work well for determining sex. (This is also similar to the threshold noted by @castedo in #43). Here's a summary plot (which is also included in the PR) showing how those thresholds separate male and female genotypes: 

xy-chrom-snp-ratios

**Comment by willgdjones** [comment]
Agreed - that plot is convincing! Do you mind sharing the code that produced it?

**Comment by apriha** [comment]
Yep, it’s part of the PR. 🙂

In a similar manner, the construct used for this analysis can be used to process the files in the openSNP datadump as a regression test, to ensure files are being parsed correctly, enhance detection of builds, etc. I plan to push some updates related to that soon!

**Comment by willgdjones** [comment]
> In a similar manner, the construct used for this analysis can be used to process the files in the openSNP datadump as a regression test, to ensure files are being parsed correctly, enhance detection of builds, etc. I plan to push some updates related to that soon!

That's a great idea 👍

**Pull request merged**
