### PR TITLE
Feature/fix male x chromosome

### PR DESCRIPTION
**Pull request by willgdjones**
This PR fixes the issue where X and Y genotypes are duplicated in male samples. It requires deduplicating rsids in the snps dataframe, and does not currently record the duplicated rsids as discrepant snps.

### CODE REVIEW

**Comment by apriha** [comment]
Thanks Will; this is looking good. I added a means to optionally turn off the deduplication and get the duplicate SNPs.

Next I'm working on only removing double alleles in non-PAR regions. If any heterozygous SNPs are found in those regions, I'm thinking the entire SNP should be removed and made available, similar to duplicate SNPs.

And along those lines, I think the identification of Male / Female can be improved by looking for heterozygous SNPs in the non-PAR region on X...

**Comment by willgdjones** [comment]
>  I added a means to optionally turn off the deduplication and get the duplicate SNPs.

Sounds good.

Are you thinking of including the functionality you mention in this PR or adding it to a new PR?

**Comment by apriha** [comment]
> Are you thinking of including the functionality you mention in this PR or adding it to a new PR?

I just pushed the capabilities mentioned. Check it out!

**Comment by willgdjones** [comment]
Looks good 👍

**Comment by willgdjones** [comment]
I just ran this code on a sample that I know to be Female and the result was Male, so I will investigate this further.

**Comment by willgdjones** [comment]
So after investigating this - the problems lies here in the `y_snps_not_null_threshold` threshold.

I'm getting values for `y_snps_not_null / y_snps` of 0.11, 0.18 and 0.19 which is above the default threshold of 0.1.

**Comment by apriha** [comment]
Thanks, Will. We can investigate the optimal thresholds and methods as part of #49.

As far as this PR, I added a parameter to optionally turn off the deduplicating of the X and Y chromosome alleles and a means to change the thresholds when instantiating a `SNPs` object. So, I think that should address all concerns. Let me know and thanks again!

**Comment by apriha** [comment]
Also, I updated the default for the new `y_snps_not_null_threshold` that's used when instantiating a `SNPs` object for deduplicating X and Y chromosome alleles to `0.25` for now, which should at least fix the cases you identified.

**Comment by castedo** [comment]
In the R code I wrote for Gene Heritage I don't look at the Y chromo data at all (nor PAR). I only look at how many heterozygous SNPs are on the X chromosome to determine sex. From quickly checking thousands of DNA files, there is a bell curve fitting mostly between 20% to 30% and then a big spike of more than 40% of population below 2%. Between 2% and 10% there nothing. I'll attach a histogram. The males are the spike under 2% and the females are the bell curve.
The reason I don't look at the Y chromosome data all is it is too noisy. I found only looking at X chromosome to be more reliable.

**Comment by castedo** [comment]
[Rplots.pdf](https://github.com/apriha/snps/files/3992093/Rplots.pdf)
Here's a plot of % of heterozygous SNPs on non-PAR X chromosome across many thousands of DNA files. I believe the two modes perfectly segregate males vs females.

**Comment by apriha** [comment]
Awesome, thanks @castedo! I was able to reproduce almost the exact same distributions with [openSNP](https://opensnp.org) data. The approach you mention seems like it'd work well for solving #49.

**Comment by apriha** [comment]
I think this PR is good to go. The thresholds and methods for `determine_sex` are updated in #50 and should be more robust.

**Pull request merged**
